name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      # 👇 Optional: Show current files for debugging (can be removed later)
      - name: List project files
        run: ls -R

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_GRASS_028B4F71E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"

          ###### Repository/Build Configurations ######
          app_location: "/"          # Path to your index.html (use "/" if in repo root)
          api_location: ""           # No API for static sites
          output_location: ""        # Leave empty for pure HTML sites
          ###### End of Configurations ######
          
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_GRASS_028B4F71E }}
          action: "close"
